Added possibility to add listeners
graphql-dotnet/conventions pull request #100
Opened 2018-06-27 15:17 UTC by SvetlovA

This adds possibility to use custom listeners and existing listeners like DataLoaderDocumentListener to use DataLoader

2018-07-26 07:27 UTC, SvetlovA commented
Can you see my pull request or write me how can i solve N+1 problem without this solution, if it possible?

2018-10-03 17:45 UTC, Igorbek requested changes

2018-10-03 17:45 UTC, Igorbek commented on src/GraphQL.Conventions/Adapters/Engine/GraphQLEngine.cs
> +            if (listeners != null && listeners.Any())
` && listeners.Any()` is redundant and causes double enumeration. If `listeners` is empty nothing would be added.

2018-10-08 17:49 UTC, tlil approved these changes

2018-10-08 17:49 UTC, tlil commented
Sorry for the late review - thanks!

2018-10-08 17:49 UTC, merged

2018-10-13 09:28 UTC, huysentruitw commented
I'm creating a sample application with EF Core + DataLoader support and will send a PR.

2018-10-14 10:58 UTC, tlil commented
Nice, sounds good @huysentruitw