Add partial update support.
graphql-dotnet/conventions pull request #129
Opened 2019-02-11 19:23 UTC by braudabaugh

Pull Request for issue #128

2019-02-11 22:32 UTC, Igorbek requested changes
~Please see my objections here: https://github.com/graphql-dotnet/conventions/issues/128#issuecomment-462521200~ (outdated)

2019-02-16 07:59 UTC, tlil commented
@braudabaugh can you add some unit tests, please? Also cover when \Optional<>\ is attempted used for non-nullable types to prove that it handles that correctly.

2019-02-16 08:00 UTC, tlil commented
> Please see my objections here: [#128 (comment)](https://github.com/graphql-dotnet/conventions/issues/128#issuecomment-462521200)

@Igorbek You're fine with this now I take it? (from reading your further comments)

2019-02-16 08:00 UTC, tlil commented
On another note, I'm looking at better handling of this and nullable/non-nullable types in general for vNext

2019-02-16 08:11 UTC, tlil requested changes
See above comments. Thanks for this, btw

2019-03-20 20:42 UTC, braudabaugh commented
I've added the unit tests that you asked for.  If you can merge this that would be great.

2019-03-29 08:44 UTC, tlil reviewed
Thanks for adding the unit tests

2019-03-29 08:44 UTC, tlil commented on src/GraphQL.Conventions/Types/Optional.cs
> +        }
? :-) #nitpick

2019-03-29 08:45 UTC, tlil approved these changes

2019-03-29 08:45 UTC, merged

2019-06-03 22:26 UTC, mgkeen commented
Thanks for doing this! This is exactly what I needed. It doesn't look as though it's included in the latest release though. Any chance a new release can be made with this in?

2019-06-04 05:17 UTC, tlil commented
> Thanks for doing this! This is exactly what I needed. It doesn't look as though it's included in the latest release though. Any chance a new release can be made with this in?

Yep, it's on it's way. I've just been out with a back injury for the past 7-8 weeks, so been a bit slow sorry. Keep an eye out over the next few days. :-)

2019-06-04 17:03 UTC, agustin-giacchello commented
Hi all.

I am newbie with GraphQL dotnet and I was wondering, this is the only way to support partial updates with .net and GraphQL?

Regards,
Agus.

2019-06-06 23:53 UTC, mgkeen commented
@tlil sorry to hear about your injury. Hope it's healing well!

@agustin-giacchello i'm not using the conventions package yet, so wrote something to do it with the base library. I based it off the discussion here https://github.com/graphql-dotnet/graphql-dotnet/issues/541 . It's essentially along the same lines as this PR. 

It deserializes into a `Dictionary<string,object>`, then uses reflection to assign the fields that are present in the update to an object with `Option<>` properties on them.

If i had known about this conventions package when I started writing my code though, I would used it!

2019-06-16 05:26 UTC, tlil commented
> Thanks for doing this! This is exactly what I needed. It doesn't look as though it's included in the latest release though. Any chance a new release can be made with this in?

Now available in 2.1.0 @mgkeen - apologies for the delay.