Kp/convetions decimal support
graphql-dotnet/conventions pull request #173
Opened 2019-09-13 13:17 UTC by K-Pavlov

fixes #172

2019-09-13 19:14 UTC, tlil requested changes
Just a couple of things, otherwise looks good. Thanks for sorting!

2019-09-13 19:14 UTC, tlil commented on test/Tests/Execution/SchemaExecutionTests.cs
> +            var res = schema.Execute((e) => e.Query = "query { test }");
Test the result as well?

2019-09-13 19:14 UTC, tlil commented on test/Tests/SchemaBuilderHelpers.cs
> +    public static class SchemaBuilderHelpers
See comment further up - this refactor seems unnecessary.

2019-09-13 19:14 UTC, tlil commented on test/Tests/Execution/SchemaExecutionTests.cs
> +            var schema = SchemaBuilderHelpers.Schema<SchemaTypeWithDecimal>();
Without the refactoring done further down, you can simply have `SchemaExecutionTests` derive from `ConstructionTestBase` and use `Schema<SchemaTypeWithDecimal>()` here.

2019-09-13 20:49 UTC, K-Pavlov commented
Check, will resolve them tommorow

2019-09-14 09:40 UTC, tlil approved these changes

2019-09-14 09:40 UTC, merged

2019-10-04 08:03 UTC, shoe-diamente commented
Is there some pre-release / nightly package available that includes this fix?