Compatiblity with GraphQL 3.0.0-preview-1719
graphql-dotnet/conventions pull request #206
Opened 2020-09-01 21:45 UTC by BoBiene

Based on graphql-dotnet#194

Currently the Unit-Test Tests.Adapters.Engine.Bugs.BugUnexpectedTypeTests.Can_Resolve_Null_NonNull_Query fails.
@clangelov can you please assist fixing this?

2020-09-02 17:19 UTC, clangelov commented
> Based on #194
> 
> Currently the Unit-Test Tests.Adapters.Engine.Bugs.BugUnexpectedTypeTests.Can_Resolve_Null_NonNull_Query fails.
> @clangelov can you please assist fixing this?

Sure :) I think the issue is related to your changes in the GraphTypeAdapter.cs,  you need to use the same method overload as from my PR  https://github.com/graphql-dotnet/conventions/pull/205 for Schema.RegisterTypes(...)  and probably it will resolve the issue. I will be able to give you more feedback on Thursday

2020-09-03 06:58 UTC, clangelov commented
> Based on #194
> 
> Currently the Unit-Test Tests.Adapters.Engine.Bugs.BugUnexpectedTypeTests.Can_Resolve_Null_NonNull_Query fails.
> @clangelov can you please assist fixing this?

In the GraphTypeAdapter DeriveSchema method you need to change it to 

```
// build params IGraphType[] types istead of Types[]
            var possibleTypes = interfaces 
                .Where(t => !t.IsIgnored)
                .SelectMany(t => t.PossibleTypes)
                .Select(typeInfo => (typeInfo.IsIgnored || !typeInfo.IsNullable || typeInfo.Interfaces.Any(x => x.IsIgnored == true))
                    ? null
                    : DeriveType(typeInfo)
                )
                .Where(x => x != null)
                .GroupBy(t => t.Name)
                .Select(g => g.First())
                .ToArray();
            var schema = new Schema(new FuncDependencyResolver(DeriveTypeFromTypeInfo)) // this one can remain the same 
            {
                Query = DeriveOperationType(schemaInfo.Query),
                Mutation = DeriveOperationType(schemaInfo.Mutation),
                Subscription = DeriveOperationType(schemaInfo.Subscription),
            };
            schema.RegisterTypes(possibleTypes); // register proper IGraphType[] types which won't fail with unrecognized types
```

and the test should pass. It's kind-a difficult to explain why this is needed, but when you have larger and more complex schema, when you pass Type[] it just fails to properly register the graph types and queries start to fail

2020-09-03 07:15 UTC, BoBiene commented
Thank you @clangelov 👍
@tlil can you please review this Pullrequest

2020-09-04 06:51 UTC, BoBiene commented
@sungam3r, can you please take a look at this?

2020-09-04 07:15 UTC, tlil commented
Yes, will review this weekend. Thanks!

2020-09-04 13:23 UTC, sungam3r commented
I can review this next week after my vacation.

2020-09-10 10:31 UTC, jdomnick commented
I just fixed two issues in this branch I had with subscriptions (Type name generation and subscription execution).
Tests are still running successfully.

2020-09-13 11:20 UTC, sungam3r requested changes
I didn't look in great detail. I do not use this project and therefore am not an expert. I have seen two major flaws:
1. Sync over async. I propose remove such methods and keep only async ones.
2. Dependency on GraphQL serializer. I propose to remove dependency and allow to user decide which to use.

2020-09-13 11:20 UTC, sungam3r commented on src/GraphQL.Conventions/Adapters/Engine/GraphQLEngine.cs
> +        public string SerializeResult(ExecutionResult result) => SerializeResultAsync(result).GetAwaiter().GetResult();
I strongly do not recommend you to have sync over async methods.

2020-09-13 11:20 UTC, sungam3r commented on src/GraphQL.Conventions/Adapters/ResolutionContext.cs
> +        public IEnumerable<string> Path => FieldContext.Path.Select(o=> o?.ToString());
```suggestion
        public IEnumerable<string> Path => FieldContext.Path.Select(o => o?.ToString());
```

2020-09-13 11:20 UTC, sungam3r commented on src/GraphQL.Conventions/Adapters/Types/IdGraphType.cs
> +    public class IdGraphType : ScalarGraphType
Why do we need this type at all, if GraphL.NET already has one?

2020-09-13 11:20 UTC, sungam3r commented on src/GraphQL.Conventions/GraphQL.Conventions.csproj
> +		<PackageReference Include="GraphQL.NewtonsoftJson" Version="3.0.0" />
I recommend that you follow a general strategy and not make dependencies on a particular serializer.

2020-09-13 11:20 UTC, sungam3r commented on src/GraphQL.Conventions/GraphQL.Conventions.csproj
> +		<GenerateDocumentationFile>false</GenerateDocumentationFile>
Why?

2020-09-13 11:20 UTC, sungam3r commented on src/GraphQL.Conventions/GraphQL.Conventions.csproj
> +	</PropertyGroup>
```suggestion
```
I'm sure this already works by default.

2020-09-13 11:20 UTC, sungam3r commented on src/GraphQL.Conventions/GraphQL.Conventions.csproj
> +		<LangVersion>7.3</LangVersion>
```suggestion
		<LangVersion>latest</LangVersion>
```

2020-09-13 11:20 UTC, sungam3r commented on src/GraphQL.Conventions/Web/RequestHandler.cs
> +                return  new Response(request, result);
```suggestion
                return new Response(request, result);
```

2020-09-13 11:20 UTC, sungam3r commented on src/GraphQL.Conventions/Execution/UserContextExtensions.cs
> +        public static IUserContext GetUserContext<T>(this ResolveFieldContext<T> context) => GetValue<IUserContext>(context.UserContext);
Maybe it worth changing ResolveFieldContext to IResolveFieldContext everywhere in this file?

2020-09-13 11:20 UTC, sungam3r commented on test/GraphQL.Conventions.Tests/Adapters/Engine/ErrorTests.cs
> +        private const bool CanExposeExceptionData = false; // is currently not possible.
It is possible now, see `IErrorInfoProvider`.

2020-09-13 11:20 UTC, sungam3r commented on test/GraphQL.Conventions.Tests/GraphQL.Conventions.Tests.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
Consider changing test TFM to netcoreapp3.1.

2020-09-13 11:21 UTC, sungam3r commented
@BoBiene reviewed

2020-11-03 21:24 UTC, tlil commented
Seems like this has now been incorporated into https://github.com/graphql-dotnet/conventions/pull/194#issuecomment-719232580? Does that mean we can close this as a dup, @BoBiene and @schabannes?

2020-11-14 06:27 UTC, closed without merging